### ISSUE TITLE
Add support of PBS system (a new finishing flag for worker)

### ISSUE THREAD

**Issue by jar091** [armadillica/flamenco-worker-python#4]
To run a job on the HPC cluster, it needs to set up a Portable Batch System (PBS). This PBS requires a small time for running a job. It will be good idea to have a new flag (in the setup of worker), which can end the worker after finishing of the first task. For the next task it will be to run the new job with the new worker.

**Comment by fsiddi** [comment]
FYI, this started as an email conversation. Maybe @jar091 has a patch for it?

**Comment by sybrenstuvel** [comment]
implemented in 7b0b641dfb3159c746e95f872ae24e02ba44b15e. You can now pass `--single` or `-1` and the worker will shut down after executing a single task.
