### ISSUE TITLE
Sanity Check Test Write is Not Writeable

### ISSUE THREAD

**Issue by rickpalo** [armadillica/flamenco-worker-python#8]
I am getting the following error on Ubuntu: 
ERROR flamenco_worker.worker.FlamencoWorker Pre-task sanity check failed: /render/_flamenco is not writable, waiting until it succeeds.

Is '/render/' the same directory as the Render Path Replacement Variable?  Also, should the file/folder '_flamenco' already exist, or is that what is being written?

Thank you!

**Comment by sybrenstuvel** [comment]
You'll have to update the default `flamenco-worker.cfg` to suit your needs. Add writability/readability checks as you see fit. If you don't need the feature, just delete the whole section from the config file.

**Comment by rickpalo** [comment]
Thank you!  That was the problem; I thought the render path in the error was coming from the variables in the manager setup.  Thanks for the quick reply!
