### ISSUE TITLE
ZLIB Not Found

### ISSUE THREAD

**Issue by rickpalo** [armadillica/flamenco-worker-python#9]
Good morning,
A render is failing with the following message. 
>/usr/lib/blender/blender: libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/local/cuda/lib64/libpng16.so.16)

I have ZLIB installed (ubuntu 18.04) but the version is 1.2.11.  Is the error due to the different version or because it is not located where Blender is looking for it?

Thank you

**Comment by sybrenstuvel** [comment]
This seems to be an issue with Blender, not with Flamenco Worker. Can you run Blender by itself?

**Comment by rickpalo** [comment]
Yes, Blender runs both through the GUI and the command line.  When I run the command, copied from the log file (below), that caused the error, I don't get the ZLIB error.

>2019-02-14T13:09:44-0700: Manager assigned task 5c65c73ec9539e04c9a5ee01 to worker 192.168.1.xx (xx)
2019-02-14T20:09:44.350273+00:00: blender_render: Starting
2019-02-14T20:09:44.350643+00:00: Executing /usr/bin/blender --enable-autoexec -noaudio --background /mnt/xxx/flamenco/flamencoTest.flamenco.blend --render-output '/mnt/xxx/flamenco/tmp__intermediate-2019-02-14_195334/######' --render-format PNG --render-frame 2
2019-02-14T20:09:44.638495+00:00: pid=11356 > /usr/lib/blender/blender: /yyy/flamenco/flamenco-worker-2.2.1/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/local/cuda/lib64/libpng16.so.16)
2019-02-14T20:09:44.639458+00:00: blender_render.(task_id=5c65c73ec9539e04c9a5ee01, command_idx=0): Error executing: Command  /usr/bin/blender --enable-autoexec -noaudio --background /mnt/xxx/flamenco/flamencoTest.flamenco.blend --render-output '/mnt/xxx/flamenco/tmp__intermediate-2019-02-14_195334/######' --render-format PNG --render-frame 2 (pid=11356) failed with status 1

**Comment by sybrenstuvel** [comment]
That's so strange. Can you give it a try with an official build of Blender, either from [the download page](https://blender.org/download) or a [daily build](https://builder.blender.org/download)?

**Comment by rickpalo** [comment]
I downloaded the daily build today.  Using that solved the error with Blender, and frames rendered successfully.  I was getting the same ZLIB error  with ffmpeg during the create video task (the output should be PNG; not sure why the create video task was even there) .  I pointed the config file to the /usr/share/ffmpeg instead of the original /usr/bin/ffmpeg.  That eliminated the ZLIB error.  
I am now getting the following error:
>create_video.(task_id=5c66e61bc9539e14ab223b79, command_idx=0): Error in settings: FFmpeg command '/usr/share/ffmpeg' not found on $PATH
When I echo my $PATH, it includes /usr/share/ffmpeg.  This may not be a flamenco problem at all.  Any ideas?

**Comment by sybrenstuvel** [comment]
Is `/usr/share/ffmpeg` a directory or a file? You need to point Flamenco to a file.

**Comment by rickpalo** [comment]
You are right.  I switched back to /usr/bin/ffmpeg and get the following error: 
>Executing /usr/bin/ffmpeg -r 24 -pattern_type glob -i '/mnt/nfs/blender/flamenco/xxx/*.png' -c:v h264 -crf 23 -g 18 -y -bf 0 /mnt/nfs/blender/flamenco/xxx/flamencoTest-1-2.mkv
pid=29954 > /usr/bin/ffmpeg: /yyy/flamenco/flamenco-worker-2.2.1/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/local/cuda/lib64/libpng16.so.16)
create_video.(task_id=5c6729f4c9539e18ca0fd4aa, command_idx=0): Error executing: Command /usr/bin/ffmpeg -r 24 -pattern_type glob -i '/mnt/nfs/blender/flamenco/xxx/*.png' -c:v h264 -crf 23 -g 18 -y -bf 0 /mnt/nfs/blender/flamenco/xxx/flamencoTest-1-2.mkv (pid=29954) failed with status 1

**Comment by sybrenstuvel** [comment]
It looks like your system isn't set up correctly, and is using an outdated Cuda install. Check `/etc/ld.so.conf.d/*` and `/etc/ld.so.conf` to see if there are any bad entries in there, and re-run `sudo ldconfig`. As such, this isn't a problem with Flamenco or Blender itself.

**Comment by rickpalo** [comment]
Thanks for your help narrowing this down.  I re-installed Cuda without any change.  I finally found the solution here (https://ubuntuforums.org/showthread.php?t=2375927).  That might be the same things as re-running `ldconfig`.  I missed that suggestion the first time I skimmed through your message.
